### ISSUE TITLE
Kaffeine does not like alternative do ... while syntax

### ISSUE THREAD

**Issue by felixge** [weepy/kaffeine#23]
I sometimes use this:

```
do {
} while (condition);
```

But it seems kaffeine struggles with it:

```
/var/git/transloader.transload.it/api2/node_modules/transloadit/command.js (compiled):28
    }) while (arg.pair == true);
       ^^^^^

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
SyntaxError: Unexpected token while
    at Module._compile (module.js:399:25)
    at /usr/local/lib/node_modules/kaffeine/lib/index.js:94:12
    at Object..js (/var/git/transloader.transload.it/api2/node_modules/transloadit/transloadit.js:9:12)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/var/git/transloader.transload.it/api2/node_modules/transloadit/tool.js (compiled):3:11)
    at Module._compile (module.js:404:26)
    at /usr/local/lib/node_modules/kaffeine/lib/index.js:94:12
    at Object..js (/var/git/transloader.transload.it/api2/node_modules/transloadit/transloadit.js:9:12)
```

I did not find a workaround for this one yet.

**Comment by weepy** [comment]
Lol. I didn't know that was valid js myself.
Tapped on my fone

On 16 Apr 2011, at 18:11, felixge
reply@reply.github.com
wrote:

**Comment by weepy** [comment]
This should be an easy fix - just need to handle the do keyword. will get to it next week

**Comment by weepy** [comment]
ok - i found the issue, I have a fix but not had a chance to try it - I think changing like 617 of token.js to :

<pre>
var blockKeywords = "do if for while else try catch function".split(" ")
</pre>

should fix it. At the moment it thinks that do is a function call and hence the block is actually an anonymous function.

**Comment by weepy** [comment]
Hi - I just pushed a fix that seems to work ok for this do problem

cheers

Jonah

**Comment by felixge** [comment]
I think this works now. But since I still get compiled errors I'm not 100% sure. I'll re-open if I see issues with this again.
